<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Admin_model extends CI_Model
{

    public $table = 'admin';
    public $id = 'id_admin';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_admin,nama_admin,username_admin,password_admin,level_admin');
        $this->datatables->from('admin');
        //add this line for join
        //$this->datatables->join('table2', 'admin.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/read/$1'),'Read')." | ".anchor(site_url('admin/update/$1'),'Update')." | ".anchor(site_url('admin/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_admin');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_admin', $q);
	$this->db->or_like('nama_admin', $q);
	$this->db->or_like('username_admin', $q);
	$this->db->or_like('password_admin', $q);
	$this->db->or_like('level_admin', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_admin', $q);
	$this->db->or_like('nama_admin', $q);
	$this->db->or_like('username_admin', $q);
	$this->db->or_like('password_admin', $q);
	$this->db->or_like('level_admin', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Admin_model.php */
/* Location: ./application/models/Admin_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-23 05:41:37 */
/* http://harviacode.com */