<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kegiatan_model extends CI_Model
{

    public $table = 'kegiatan';
    public $id = 'id_kegiatan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('kegiatan.id_kegiatan,kategori.nama_kategori,kegiatan.nama_kegiatan,kegiatan.waktu_kegiatan,kegiatan.gambar_kegiatan,kegiatan.keterangan_kegiatan');
        $this->datatables->from('kegiatan');
        $this->datatables->join('kategori', 'kegiatan.id_kategori = kategori.id_kategori');

        $this->datatables->add_column('action', anchor(site_url('kegiatan/update/$1'),'Update')." | ".anchor(site_url('kegiatan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_kegiatan');

        $this->datatables->add_column('gambars', "<img width='50' src='./assets/upload/$1'>", 'gambar_kegiatan');


        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kegiatan', $q);
        $this->db->or_like('id_kategori', $q);
        $this->db->or_like('nama_kegiatan', $q);
        $this->db->or_like('waktu_kegiatan', $q);
        $this->db->or_like('gambar_kegiatan', $q);
        $this->db->or_like('keterangan_kegiatan', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kegiatan', $q);
        $this->db->or_like('id_kategori', $q);
        $this->db->or_like('nama_kegiatan', $q);
        $this->db->or_like('waktu_kegiatan', $q);
        $this->db->or_like('gambar_kegiatan', $q);
        $this->db->or_like('keterangan_kegiatan', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kegiatan_model.php */
/* Location: ./application/models/Kegiatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-24 06:16:18 */
/* http://harviacode.com */